/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author tavoberry
 */
public class VentanaPlumon extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPlumon
     */
    public VentanaPlumon() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        txtColor = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        txtCodigoDeBarras = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnDestapar = new javax.swing.JButton();
        btnTapar = new javax.swing.JButton();
        btnPintar = new javax.swing.JButton();
        lblMensaje = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Plumon");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Marca");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 19, -1, -1));

        jLabel2.setText("Color");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel3.setText("Precio");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel4.setText("Código de Barras");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        txtMarca.setText(" ");
        getContentPane().add(txtMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 153, -1));
        getContentPane().add(txtColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 153, -1));
        getContentPane().add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 153, -1));
        getContentPane().add(txtCodigoDeBarras, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 151, -1));

        btnGuardar.setText("Guardar");
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 14, 100, -1));

        btnDestapar.setText("Destapar");
        getContentPane().add(btnDestapar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, -1, -1));

        btnTapar.setText("Tapar");
        getContentPane().add(btnTapar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 100, -1));

        btnPintar.setText("Pintar");
        getContentPane().add(btnPintar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 100, -1));

        lblMensaje.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblMensaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMensaje.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 400, 14));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPlumon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPlumon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPlumon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPlumon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPlumon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnDestapar;
    public javax.swing.JButton btnGuardar;
    public javax.swing.JButton btnPintar;
    public javax.swing.JButton btnTapar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JLabel lblMensaje;
    public javax.swing.JTextField txtCodigoDeBarras;
    public javax.swing.JTextField txtColor;
    public javax.swing.JTextField txtMarca;
    public javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
